### ISSUE TITLE
Provide better support for a "root-consumer-span"?

### ISSUE THREAD

**Issue by alaendle** [mtth/tracing#24]
Similar to #11 - should we strive for a similar API extension that was done to support root-producers? Or will this clutter the API?

As always implementing this is already possible:
```haskell
TC.rootSpanWith (ZPK.addInheritedTag (cs "service.instance.id") serviceInstance . \builder -> builder { TC.builderTags = M.insert (cs "z.k") (JSON.toJSON "CONSUMER") (TC.builderTags builder) })
```

Might be a rather rare scenario - in my case we have a simple MQTT3 producer which isn't able to create/transfer traces on it's own, so our consumer should create the root span.

**Comment by mtth** [comment]
Sounds reasonable to me. I'd be happy to review a PR that does the same as https://github.com/mtth/tracing/pull/15 for consumers.
